### ISSUE TITLE
Is it working with latest version?

### ISSUE THREAD

**Issue by vbarrier** [n8nhackers/n8n-nodes-document-generator#2]
### Describe the bug

Hi, 

thank you for your useful node! I made some workflows with it but since the latest version of n8n I have lot of weird bugs: 

`ERROR: Missing helper: "Start"`

or 

`ERROR: (((intermediate value)(intermediate value) && lookupProperty(...)) || alias2).call is not a function`

### Describe the expected behavior

A working node :)

### What is your Node.js version?

18

### What is your n8n version?

0.199.0

### What is your n8n-nodes-text-manipulation version?

1.0.3

### What operating system are you seeing the problem on?

Other (enter below with the version)

### Operating system version (or if other, then please fill in complete name and version)

Docker

**Comment by mcolomer** [comment]
Hi @vbarrier ,

Thank you for your kindly words.

Yes, node works with 0.199.*
Your error is related with the Start node, instead of the n8n-nodes-document-generator.

Start node is RIP at 0.199. This means that it doesn't work.
You need to delete Start node, and add the right trigger to start flow.
If you only want to start manually, add Manually trigger and it will work.

You have a sample workflow here
`
{
  "meta": {
    "instanceId": "14c5980141526fbb38db85208103f515afa76de9c8760a23a1771b4ed940dc7b"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "fedbfde3-7fa0-4c8f-8efc-12aea4a4b4ce",
      "name": "On clicking 'execute'",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        580,
        420
      ]
    },
    {
      "parameters": {
        "oneTemplate": true,
        "template": "<ul id=\"customer_list\">\n  {{#each items}}\n  <li>{{name}}: {{email}}</li>\n  {{/each}}\n</ul>"
      },
      "id": "1b6fc745-8b3e-426a-b076-4c017eaf9b47",
      "name": "DocumentGenerator",
      "type": "n8n-nodes-document-generator.DocumentGenerator",
      "typeVersion": 1,
      "position": [
        1000,
        420
      ]
    },
    {
      "parameters": {
        "operation": "getAllPeople"
      },
      "id": "72875e87-8721-4693-9f9a-9ff019ab254d",
      "name": "Customer Datastore",
      "type": "n8n-nodes-base.n8nTrainingCustomerDatastore",
      "typeVersion": 1,
      "position": [
        800,
        420
      ]
    }
  ],
  "connections": {
    "On clicking 'execute'": {
      "main": [
        [
          {
            "node": "Customer Datastore",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Customer Datastore": {
      "main": [
        [
          {
            "node": "DocumentGenerator",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
`

Let me know if you have any other doubt.

Take care!

**Comment by vbarrier** [comment]
Sorry found the problem related to space in variables!

**Comment by vbarrier** [comment]
Thank you for complete reply :)
